name = "M17 Hugo"
license = "CC BY 3.0"
licenselink = "https://creativecommons.org/licenses/by/3.0/"
description = "M17 port of the Themefisher’s Meghna Template"
homepage = "https://m17project.org"
tags = ['landing-page', 'google-analytics', 'fast', 'modern', 'minimal', 'minimalistic', 'hugo-theme', 'hugo-templates', 'bootstrap', 'blog', 'responsive', 'portfolio', 'single-page', 'dark', 'clean', 'simple', 'company', 'creative', 'contact-form', 'custom-themes', 'mobile']
features = ['bootstrap','responsive']
min_version = "0.58.0"

[author]
  name = "KC1AWV"
  homepage = "https://kc1awv.net/"
